import { describe,expect,it } from 'vitest';
import { cleanEpisodeName,cleanReleaseName,groupDebridCatalog } from './media-parser';

describe('AllDebrid catalog grouping',()=>{
  it('groups season magnets and episodes into one series title',()=>{const result=groupDebridCatalog([{id:1,filename:'MA_SERIES Season 3 1080p',statusCode:4,videoFiles:[{index:0,name:'MA_SERIES_S03E03_1080p.mkv',size:10,path:''}]},{id:2,filename:'MA SERIES S02 WEB-DL',statusCode:4,videoFiles:[{index:0,name:'MA.SERIES.S02E01.mkv',size:10,path:''}]}]);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({title:'MA SERIES',category:'series',seasonCount:2});expect(result[0].episodes.map(e=>[e.season,e.episode])).toEqual([[2,1],[3,3]])});
  it('keeps standalone files as movies',()=>{const [movie]=groupDebridCatalog([{id:7,filename:'Example Movie 2024 1080p',statusCode:4,videoFiles:[{index:0,name:'Example.Movie.2024.1080p.mkv',size:20,path:''}]}]);expect(movie).toMatchObject({title:'Example Movie',category:'movie',year:2024});expect(movie.episodes[0]).toMatchObject({magnetId:7,file:0})});
  it('cleans release indexes, language tags, and broken episode suffixes',()=>{expect(cleanReleaseName('03 Shrek The Third - Animation 2007 Eng Fre Ita Spa')).toBe('Shrek The Third - Animation 2007');expect(groupDebridCatalog([{id:8,filename:'03 Shrek The Third - Animation 2007 Eng Fre Ita Spa',statusCode:4,videoFiles:[{index:0,name:'03 Shrek The Third - Animation 2007 Eng Fre Ita Spa.mkv',size:20,path:''}]}])[0].title).toBe('Shrek the Third');expect(cleanEpisodeName('The Mentalist (2008) - S02E01 - 1Redemption (',1)).toBe('Redemption')});
  it('merges aliases and keeps only the best copy of each episode',()=>{const result=groupDebridCatalog([{id:1,filename:'Friends Season 01',statusCode:4,videoFiles:[{index:0,name:'Friends.S01E01.720p.mkv',size:10,path:''}]},{id:2,filename:'Friends.S01.1080p.BluRay',statusCode:4,videoFiles:[{index:0,name:'Friends.S01E01.1080p.mkv',size:20,path:''},{index:1,name:'Friends.S01E02.1080p.mkv',size:20,path:''}]}]);expect(result).toHaveLength(1);expect(result[0].episodes).toHaveLength(2);expect(result[0].episodes[0]).toMatchObject({magnetId:2,season:1,episode:1,size:20})});
  it('merges Friends releases without swallowing Smiling Friends',()=>{const result=groupDebridCatalog([{id:3,filename:'Friends COMPLETE',statusCode:4,videoFiles:[{index:0,name:'Friends.S01E01.mkv',size:10,path:''}]},{id:4,filename:'Friends (1994) Season 2',statusCode:4,videoFiles:[{index:0,name:'Friends.S02E01.mkv',size:10,path:''}]},{id:5,filename:'Smiling Friends S01',statusCode:4,videoFiles:[{index:0,name:'Smiling.Friends.S01E01.mkv',size:10,path:''}]}]);expect(result.map(item=>item.title).sort()).toEqual(['Friends','Smiling Friends']);expect(result.find(item=>item.title==='Friends')).toMatchObject({year:1994,seasonCount:2})});
  it('deduplicates movie releases by canonical title and year',()=>{const result=groupDebridCatalog([{id:1,filename:'One Battle After Another 2025',statusCode:4,videoFiles:[{index:0,name:'One.Battle.After.Another.2025.1080p.mkv',size:10,path:''}]},{id:2,filename:'One Battle After Another 2025 2160p',statusCode:4,videoFiles:[{index:0,name:'One.Battle.After.Another.2025.2160p.mkv',size:30,path:''}]}]);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({title:'One Battle After Another',year:2025});expect(result[0].episodes[0].magnetId).toBe(2)});
  it('normalizes and merges numbered Star Wars release variants',()=>{const result=groupDebridCatalog([{id:20,filename:'Star Wars Episode 9 (2019) The Rise Of Skywalker',statusCode:4,videoFiles:[{index:0,name:'Star.Wars.Episode.9.2019.The.Rise.Of.Skywalker.mkv',size:10,path:''}]},{id:21,filename:'Star Wars Episode IX The Rise Of Skywalker 2020',statusCode:4,videoFiles:[{index:0,name:'Star.Wars.Episode.IX.The.Rise.Of.Skywalker.2020.Hybrid.mkv',size:20,path:''}]}]);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({title:'Star Wars: Episode IX – The Rise of Skywalker',year:2019});expect(result[0].episodes[0].magnetId).toBe(21)});
  it('uses a meaningful magnet title and ignores bonus videos',()=>{const result=groupDebridCatalog([{id:30,filename:'INTERSTELLAR',statusCode:4,videoFiles:[{index:0,name:'00001.m2ts',size:30,path:''},{index:1,name:'00002.m2ts',size:20,path:''}]},{id:31,filename:'Zootopia (2016)',statusCode:4,videoFiles:[{index:0,name:'Zootopia.2016.mkv',size:30,path:''},{index:1,name:'Zootopia - The Roundtables-behindthescenes.mkv',size:5,path:''}]}]);expect(result.map(item=>item.title).sort()).toEqual(['Interstellar','Zootopia']);});
  it('ignores tiny promotional videos bundled with a movie',()=>{const result=groupDebridCatalog([{id:32,filename:'Joker (2019)',statusCode:4,videoFiles:[{index:0,name:'Joker.2019.mkv',size:2_000,path:''},{index:1,name:'Becoming Joker.mkv',size:20,path:''},{index:2,name:'RARBG.com.mp4',size:1,path:''}]}]);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({title:'Joker',year:2019})});
  it('recognizes standalone Malcolm season folders from their episode names',()=>{const result=groupDebridCatalog([{id:40,filename:'Season 5',statusCode:4,videoFiles:[{index:0,name:'09. Dirty Magazine.mov',size:10,path:''},{index:1,name:"20. Victor's Other Family.avi",size:10,path:''}]}]);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({title:'Malcolm in the Middle',year:2000,category:'series'});});
  it('recognizes 01x02 episode notation as a series',()=>{const [result]=groupDebridCatalog([{id:50,filename:'Futurama (1999-2024)',statusCode:4,videoFiles:[{index:0,name:'Futurama - 01x02 - La serie è atterrata.mkv',size:10,path:''},{index:1,name:'Futurama - 02x03 - Attacco alieno.mkv',size:10,path:''}]}]);expect(result).toMatchObject({title:'Futurama',category:'series',seasonCount:2});expect(result.episodes.map(e=>[e.season,e.episode])).toEqual([[1,2],[2,3]])});
  it('groups the numbered Avatar pack into its three seasons and drops bonuses',()=>{const [result]=groupDebridCatalog([{id:51,filename:"AVATAR MAITRE DE L'AIR",statusCode:4,videoFiles:[{index:0,name:"Avatar Le Dernier Maitre De L'Air - 01.mkv",size:10,path:''},{index:1,name:"Avatar Le Dernier Maitre De L'Air - 21.mkv",size:10,path:''},{index:2,name:"Avatar Le Dernier Maitre De L'Air - 61.mkv",size:10,path:''},{index:3,name:"Avatar Le Dernier Maitre De L'Air - Bonus - 01.mkv",size:5,path:''}]}]);expect(result).toMatchObject({title:'Avatar: The Last Airbender',year:2005,category:'series',seasonCount:3});expect(result.episodes.map(e=>[e.season,e.episode])).toEqual([[1,1],[2,1],[3,21]])});
  it('gives same-named series from different years unique stable identities',()=>{const input=[{id:50,filename:'Archive Show (1994) S01',statusCode:4,videoFiles:[{index:0,name:'Archive.Show.1994.S01E01.mkv',size:10,path:''}]},{id:51,filename:'Archive Show (2025) S01',statusCode:4,videoFiles:[{index:0,name:'Archive.Show.2025.S01E01.mkv',size:10,path:''}]}];const first=groupDebridCatalog(input);const second=groupDebridCatalog([...input].reverse());expect(first).toHaveLength(2);expect(new Set(first.map(item=>item.id)).size).toBe(2);expect(first.map(item=>item.id).sort()).toEqual(second.map(item=>item.id).sort());expect(first.map(item=>item.year).sort()).toEqual([1994,2025]);});
  it('identifies the production Lost collection instead of The O.C.',()=>{const [result]=groupDebridCatalog([{id:194747691,filename:'LOST.Integrale.2004-2010.MULTi.1080p.Bluray.X265.10bit-Papaya',statusCode:4,videoFiles:[{index:111,name:'Lost S01E01 (Pilot Part One) Multi Papaya.mkv',size:1078343350,path:''}]}]);expect(result).toMatchObject({title:'Lost',year:2004,category:'series'});});
});
