'use client';
import { useCallback, useEffect, useState } from 'react';
import { Film, Play, RefreshCw } from 'lucide-react';
import { Route } from './routing';
type File={index:number;name:string;size:number;path:string}; type Magnet={id:number;filename:string;statusCode:number;videoFiles:File[]};
const clean=(name:string)=>name.replace(/\.[^.]+$/,'').replace(/[._]/g,' ').replace(/\b(1080p|2160p|720p|web[- ]?dl|bluray|x26[45]|hevc|aac).*$/i,'').replace(/\s+/g,' ').trim();
const size=(bytes:number)=>bytes?`${(bytes/1024**3).toFixed(1)} GB`:'Video';
export function DebridLibrary({navigate,mode='rail'}:{navigate:(route:Route)=>void;mode?:'rail'|'page'}){const [items,setItems]=useState<Array<{id:string;magnetId:number;file:number;title:string;subtitle:string}>>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/debrid/magnets',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Your library is unavailable.');setItems((data.magnets as Magnet[]).filter(m=>m.statusCode===4).flatMap(m=>m.videoFiles.map(file=>({id:`${m.id}-${file.index}`,magnetId:m.id,file:file.index,title:clean(file.name)||clean(m.filename),subtitle:`My Library · ${size(file.size)}`}))))}catch(reason){setError(reason instanceof Error?reason.message:'Your library is unavailable.')}finally{setLoading(false)}},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);return <section className={mode==='page'?'library-page':'media-rail-section debrid-rail'} aria-label="My Library"><div className="section-title"><h2>My Library</h2><span>Ready to stream from your AllDebrid account</span><button className="library-refresh" onClick={()=>void load()} aria-label="Refresh My Library"><RefreshCw className={loading?'spin':''}/></button></div>{loading?<div className="debrid-status"><RefreshCw className="spin"/>Loading your titles…</div>:error?<div className="debrid-status debrid-error"><Film/><span><strong>Connect your library</strong>{error}</span></div>:items.length===0?<div className="debrid-status"><Film/><span><strong>No ready videos</strong>Ready magnets appear here automatically.</span></div>:<div className={mode==='page'?'library-grid':'media-rail'}>{items.map(item=><button className="library-card" key={item.id} onClick={()=>navigate({section:'debrid',id:String(item.magnetId),file:item.file,title:item.title})}><span className="library-card-art"><b>{item.title.slice(0,1)}</b><i><Play fill="currentColor"/></i></span><strong>{item.title}</strong><small>{item.subtitle}</small></button>)}</div>}</section>}
export function DebridDetails({route,navigate,onClose}:{route:Route;navigate:(route:Route)=>void;onClose:()=>void}){return <div className="modal-backdrop"><article className="detail-modal debrid-detail"><button className="icon-button modal-close" onClick={onClose} aria-label="Close title details">×</button><div className="detail-art tone-space"><div className="detail-monogram">{route.title?.slice(0,1)||'K'}</div><div className="detail-gradient"/></div><div className="detail-content"><p className="k-original"><b>K</b> MY LIBRARY</p><h2>{route.title}</h2><button className="primary-action" onClick={()=>navigate({section:'stream',id:route.id,file:route.file,title:route.title})}><Play fill="currentColor"/>Play</button><div className="detail-grid"><p className="detail-description">Available now from your authorized AllDebrid library. Kheyflix streams it through a private range-enabled backend connection.</p><dl><div><dt>Source: </dt><dd>My Library</dd></div><div><dt>Availability: </dt><dd>Ready to stream</dd></div></dl></div></div></article></div>}
